### ISSUE TITLE
dev-utils missing static zlib

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#33]
I try to build openwrt/lede under clearlinux, but the build step fails and complains about this:
`Build dependency: Please install a static zlib. (Missing libz.a or zlib.h)`

There requirements via ubuntu guide are these: 
```
subversion g++ zlib1g-dev build-essential git python rsync man-db libncurses5-dev gawk gettext unzip file libssl-dev wget
```

**Comment by bryteise** [comment]
So development headers are a little bit awkward with bundles at the moment. You can see what bundles contain zlib.h by running `sudo swupd search zlib.h`. I'd recommend adding os-core-dev in this case though.

**Comment by Andy2244** [comment]
Even after adding `os-core-dev` i get the same error and the compile fails.

Here are the steps:
```
git clone https://git.lede-project.org/source.git lede
cd lede

./scripts/feeds update -a
./scripts/feeds install -a

make menuconfig
```

Would be nice to get this working, so i can get rid of my ubuntu build VM as well and replace it with clearlinux.

**Comment by bryteise** [comment]
Ah interesting, our zlib needed to be rebuilt. Should be fixed in the next release.

**Comment by Andy2244** [comment]
thx, 20290 fixed the zlib problem, but now while compiling samba 4.7.4 via my lede feed i get this new error:

```
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/common/entities.ent
http://docbook.sourceforge.net/release/xsl/current/html/autoidx.xsl:4: warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/common/entities.ent"
.
.
```

It seems samba needs a local installed `docbook-style-xsl, libxslt` to compile correctly?

**Comment by bryteise** [comment]
Ugh looks like it, just to build the conf file =P.

**Comment by bryteise** [comment]
So we ship samba in storage-utils bundle, so all the things to build it should be should be in storage-utils-dev.

**Comment by Andy2244** [comment]
Still get the same error even with `storage-utils-dev`, guess i have to look into a docker version to compile Lede.

**Comment by bryteise** [comment]
Hrm I'll see about building samba outside of mock myself then at some point... Would building in mock be a better solution than docker?

**Comment by Andy2244** [comment]
Never heard of "mock" so i guess docker would be better for me personally, since i already know how to use it. I was hoping that just adding some few missing requirements would work to directly build lede/samba, without learning, setting up the docker compile workflow for lede+samba.

I guess docker will pay off in the long run, since it will always include a tested/viable environment to build lede, compared to update, fix clearlinux. Its a shame since it seemed samba might have been the only package that fails, make was about 80% done until it hit samba.

PS: Its not a big problem, since i rather setup docker compile workflows over maintaining a full ubuntu/centos server distro.

**Comment by bryteise** [comment]
os-clr-on-clr ships mock which is what we use to build the disto on Clear Linux systems (well koji technically uses mock for the distro shipped packages, the developers use mock directly). The mock setup (and general developer setup) is described in the [common repo](https://github.com/clearlinux/common).

**Comment by bryteise** [comment]
Okay so I finally dug into this a bit, the reason our build works in mock is none of the docbook-xslt bits are in the chroot so samba just accepts that it can't use it and continues on. But on a real system, they are there as far as xsltproc --notnet is concerned but not useful for building it seems.

I'm not sure if/when I'll be trying to coax our docbook bits to be usable by samba and samba didn't look like it had a nice way to skip building the docs though sorry =(. Closing this issue since it was about zlib originally though. If you want to have one for docbook and samba though I will try and take a look.

**Comment by Andy2244** [comment]
Thanks for the info, i assume your time is better spend elsewhere, since i don't think there are many clearlinux users that try to cross-compile samba on it :p

**Comment by bryteise** [comment]
Yea if you were to move /usr/bin/xsltproc to somwhere else and then build you'd probably get past that error but that's pretty annoying.
